// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdOYYV0LfOp0ojLSjWMGCZGDGyYTmr44I',
    appId: '1:813499094162:web:bdf20e1205e0ab7249c24b',
    messagingSenderId: '813499094162',
    projectId: 'withatu-test-version',
    authDomain: 'withatu-test-version.firebaseapp.com',
    storageBucket: 'withatu-test-version.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_KHvJz5lT3yu-lIsKpZbYghK9kvXkjTg',
    appId: '1:813499094162:android:86fd0b62cf0c5cc049c24b',
    messagingSenderId: '813499094162',
    projectId: 'withatu-test-version',
    storageBucket: 'withatu-test-version.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6m17FIOGToDrxN_1X3-IW7tr5w0dtWI',
    appId: '1:813499094162:ios:04430b7b8c5e602749c24b',
    messagingSenderId: '813499094162',
    projectId: 'withatu-test-version',
    storageBucket: 'withatu-test-version.appspot.com',
    iosBundleId: 'com.evershare.withatutestversion.withatuTestVersion',
  );
}
